#ifndef JOINT_C_DETAIL_PREPROCESSOR_H
#define JOINT_C_DETAIL_PREPROCESSOR_H


#define JOINT_C_PP_PARAM(...)   __VA_ARGS__


#define JOINT_C_PP_CAT(A, B)    DETAIL_JOINT_C_PP_CAT_IMPL(A, B)
#define DETAIL_JOINT_C_PP_CAT_IMPL(A, B)    A##B

#define JOINT_C_PP_STRINGIZE(X) DETAIL_JOINT_C_PP_STRINGIZE(X)
#define DETAIL_JOINT_C_PP_STRINGIZE(X)  #X


#define DETAIL_JOINT_C_PP_EXPAND(...) __VA_ARGS__
#define DETAIL_JOINT_C_PP_DEFER(...) __VA_ARGS__

#define JOINT_C_PP_COUNT(...) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_COUNT_SEQ)(Dummy_, __VA_ARGS__, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0))
#define DETAIL_JOINT_C_PP_COUNT_SEQ(Dummy_, _1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,N,...) N

#define JOINT_C_PP_FOREACH(MacroName_, UserArg_, ...) DETAIL_JOINT_C_PP_EXPAND(JOINT_C_PP_CAT(DETAIL_JOINT_C_PP_FOREACH_IMPL_, JOINT_C_PP_COUNT(__VA_ARGS__))(MacroName_, UserArg_, __VA_ARGS__))

#define DETAIL_JOINT_C_PP_FOREACH_IMPL_0(M_, UA_, ...)
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_1(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_0)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_2(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_1)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_3(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_2)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_4(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_3)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_5(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_4)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_6(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_5)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_7(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_6)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_8(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_7)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_9(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_8)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_10(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_9)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_11(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_10)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_12(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_11)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_13(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_12)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_14(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_13)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_15(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_14)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_16(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_15)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_17(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_16)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_18(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_17)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_19(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_18)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_20(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_19)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_21(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_20)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_22(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_21)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_23(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_22)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_24(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_23)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_25(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_24)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_26(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_25)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_27(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_26)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_28(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_27)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_29(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_28)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_30(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_29)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_31(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_30)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_32(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_31)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_33(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_32)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_34(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_33)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_35(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_34)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_36(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_35)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_37(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_36)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_38(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_37)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_39(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_38)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_40(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_39)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_41(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_40)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_42(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_41)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_43(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_42)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_44(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_43)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_45(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_44)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_46(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_45)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_47(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_46)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_48(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_47)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_49(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_48)(M_, UA_, __VA_ARGS__))
#define DETAIL_JOINT_C_PP_FOREACH_IMPL_50(M_, UA_, E_, ...)  M_(E_, UA_) DETAIL_JOINT_C_PP_EXPAND(DETAIL_JOINT_C_PP_DEFER(DETAIL_JOINT_C_PP_FOREACH_IMPL_49)(M_, UA_, __VA_ARGS__))


#endif
