package test
{

    enum Enum
    {
        Value1,
        Value2,
        Value3 = 42,
        Value4
    }

    interface IEnumTests
    {
        string StringRepresentation(Enum e);
        Enum GetNextValueInRing(Enum e);
    }

    interface IEnumCallbackTests
    {
        string CallbackStringRepresentation(IEnumTests cb, Enum e);
        Enum CallbackGetNextValueInRing(IEnumTests cb, Enum e);
    }

}
