package test
{
    interface IExceptionTestsCallback
    {
        void Method();
    }

    interface IExceptionTests
    {
        void ThrowNative();
        bool CatchAll(IExceptionTestsCallback cb);
        void LetThrough(IExceptionTestsCallback cb);
    }
}

