#ifndef JOINT_ERROR_H
#define JOINT_ERROR_H


#include <joint/public/JointConfig.h>
#include <joint/public/JointCoreApi.h>


JOINT_CORE_EXTERN_C_BEGIN

    typedef enum
    {
        JOINT_CORE_ERROR_NONE = 0,
        JOINT_CORE_ERROR_CAST_FAILED = 1,
        JOINT_CORE_ERROR_EXCEPTION = 2,
        JOINT_CORE_ERROR_GENERIC = 3,
        JOINT_CORE_ERROR_NO_SUCH_BINDING = 4,
        JOINT_CORE_ERROR_NO_SUCH_MODULE = 5,
        JOINT_CORE_ERROR_NOT_IMPLEMENTED = 6,
        JOINT_CORE_ERROR_INVALID_PARAMETER = 7,
        JOINT_CORE_ERROR_OUT_OF_MEMORY = 8,
        JOINT_CORE_ERROR_IMPLEMENTATION_ERROR = 9,
        JOINT_CORE_ERROR_INVALID_INTERFACE_CHECKSUM = 10,
        JOINT_CORE_ERROR_INDEX_OUT_OF_RANGE = 11,
        JOINT_CORE_ERROR_IO_ERROR = 12,
        JOINT_CORE_ERROR_INVALID_MANIFEST = 13
    } JointCore_Error;

    JOINT_CORE_API const char* JointCore_ErrorToString(JointCore_Error err);

JOINT_CORE_EXTERN_C_END

#endif
