package joint
{
    interface IException
    {
        string GetMessage();
    }

    interface INativeLanguageException : IException
    { }

    interface INullReferenceException : IException
    { }
}
