package test
{
	interface ILifetimeListener
	{
		void OnDestroyed();
	}

	interface ILifetimeListenable
	{
		void SetListener(ILifetimeListener l);
	}

	interface ILifetimeTests
	{
		ILifetimeListenable CreateListenable();
		void CollectGarbage();
	}
}
