package test
{
	interface ISomeObject
	{
		void Method();
		i32 GetInvokationsCount();
	}

	interface IObjectTests
	{
		ISomeObject ReturnNewObject();
		ISomeObject ReturnSameObject(ISomeObject o);
		void InvokeObjectMethod(ISomeObject o);
	}
}
