package test
{
	interface IBasicTests
	{
		void Throw();

		i32 ReturnI32();
		i32 AddI32(i32 l, i32 r);
	}

	////////////////////////////////////////////////////////////////////////////////

	interface ISomeObject
	{
		void Method();
	}

	interface IObjectTests
	{
		ISomeObject ReturnObject();
		//void InvokeObjectMethod(ISomeObject o);
	}

	////////////////////////////////////////////////////////////////////////////////

	//interface ILifetimeTestsListener
	//{
		//void OnObjectDestroyed();
	//}

	//interface ILifetimeTests
	//{
		////void SetListener(ILifetimeTestsListener l);
	//}
}
