package test
{
	interface IBasicTests
	{
		void Throw();

		i32 ReturnI32();
		i32 AddI32(i32 l, i32 r);
	}

	interface ILifetimeTestsListener
	{
		void OnObjectDestroyed();
	}

	interface ILifetimeTests
	{
		//void SetListener(ILifetimeTestsListener);
	}
}
